config/routes.rb
Schedule::Application.routes.draw do
  resources :events, :only => [:show, :new, :create] do
    resources :time_tables, :only => [:edit, :create, :update] do
      member do
        post :send_created_event
        post :send_joined_event
      end
    end
  end
  root :to => "events#new"
end

app/models/base_model.rb
class BaseModel

end

app/models/event.rb
require 'permalinkable'

class Event < BaseModel
  include Mongoid::Document
  include Permalinkable

  field :title, :type => String
  field :email, :type => String
  
  embeds_many :time_tables  

  validates :title, :presence => true 
  validates :email,
            :presence => true,
            :format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }

  def availability
    map = <<-MAP
      function() {
        if (this._id == '#{id}' && this.time_tables) {
          this.time_tables.forEach(function(time_table) {
            var result = { 
              count: 1, 
              emails: [time_table.email]
            };

            if (time_table.times) time_table.times.forEach(function(time) {
              emit(time, result)
            });
          });
        }
      }
    MAP

    reduce = <<-REDUCE
      function(key, values) {
        var result = { 
          count: 0,
          emails: [] 
        };
        
        values.forEach(function(value) {
          result.count += value.count;
          result.emails = result.emails.concat(value.emails)
        });
        
        return result;
      };
    REDUCE

    collection.map_reduce(map, reduce).find().collect do |hash| 
      {
        :time => hash['_id'], 
        :count => hash['value']['count'],
        :emails => hash['value']['emails']
      }
    end
  end
  
  def max_attendance
    availability.max { |a,b| a[:count] <=> b[:count] }
  end
  
end

app/models/time_table.rb
require 'permalinkable'

class TimeTable < BaseModel
  include Mongoid::Document
  include Permalinkable
  
  field :times, :type => Array
  field :email, :type => String
  
  embedded_in :event, :inverse_of => :time_tables

  validates :email,
            :presence => true,
            :format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def show
    @event = Event.from_param(params[:id])
    @time_table = TimeTable.new
    
    respond_to do |format|
      format.html
      format.xml  { render :xml => @event }
    end
  end

  def new
    @event = Event.new

    respond_to do |format|
      format.html
      format.xml  { render :xml => @event }
    end
  end

  def create
    @event = Event.new(params[:event])
    @time_table = TimeTable.new(:email => params[:event][:email])
    @event.time_tables << @time_table
    
    respond_to do |format|
      if @event.valid? && @time_table.save
        flash[:new_event] = true
        format.html { redirect_to(edit_event_time_table_url(@event.permalink, @time_table.permalink)) }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end
  
end

app/controllers/time_tables_controller.rb
class TimeTablesController < ApplicationController
  # GET /time_tables/new
  # GET /time_tables/new.xml
  def new
    @time_table = TimeTable.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @time_table }
    end
  end

  # GET /time_tables/1/edit
  def edit
    @event = Event.from_param(params[:event_id])
    @time_table = @event.time_tables.where(:permalink => params[:id]).first
    @times = @time_table.times.to_json
  end

  # POST /time_tables
  # POST /time_tables.xml
  def create
    @event = Event.from_param(params[:event_id])
    @time_table = TimeTable.new(params[:time_table])
    @event.time_tables << @time_table

    respond_to do |format|
      if @time_table.save
        flash[:new_time_table] = true
        format.html { redirect_to(edit_event_time_table_path(@event, @time_table), :notice => 'Time table was successfully created.') }
        format.xml  { render :xml => @time_table, :status => :created, :location => @time_table }
      else
        flash[:email] = params[:time_table][:email]
        format.html { redirect_to(@event) }
        format.xml  { render :xml => @time_table.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /time_tables/1
  # PUT /time_tables/1.xml
  def update
    @event = Event.from_param(params[:event_id])
    @time_table = @event.time_tables.where(:permalink => params[:id]).first
    success = params[:time_table] && params[:time_table][:times] && 
              @time_table.update_attributes(:times => JSON.parse(params[:time_table][:times]))
    success ? update_success : update_failure
  rescue JSON::ParserError
    update_failure
  end

  # DELETE /time_tables/1
  # DELETE /time_tables/1.xml
  def destroy
    @time_table = TimeTable.find(params[:id])
    @time_table.destroy

    respond_to do |format|
      format.html { redirect_to(time_tables_url) }
      format.xml  { head :ok }
    end
  end

  def send_created_event
    event = Event.from_param(params[:event_id])
    time_table = event.time_tables.where(:permalink => params[:id]).first
    NewEventMailer.created_event(event, time_table).deliver
    render :text => '"OK"'
  end
  
  def send_joined_event
    event = Event.from_param(params[:event_id])
    time_table = event.time_tables.where(:permalink => params[:id]).first
    NewEventMailer.joined_event(event, time_table).deliver
    render :text => '"OK"'
  end

private
  
  def update_failure
    respond_to do |format|
      format.html { redirect_to(edit_event_time_table_path(@event, @time_table), :notice => 'Time table was successfully updated.') }
      format.xml  { head :ok }
    end
  end
  
  def update_success
    respond_to do |format|
      format.html { redirect_to(edit_event_time_table_path(@event, @time_table), :error => 'Error updating time table.') }
      format.xml  { render :xml => @time_table.errors, :status => :unprocessable_entity }
    end
  end


end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <div class="field">
    <%= f.label :email, "Please enter your email address" %>
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
    <%= f.label :title, "Enter a short description of your event" %>
    <%= f.text_field :title %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_what_is.html.erb
<h3>What is Schedule Butler?</h3>
<p>
  Schedule Butler is a great way for a group of people to pin down a time to meet.
</p>
<p>
  How many times have you sent an email to a group of people asking what time they
  were free?  How frustrating is it to try to figure out what the best time that
  takes into account everyone?  
</p>
<p>
  Sit back, and let the Butler do the work for you.
</p>

app/views/events/new.html.erb
<% content_for :sidebar do %>
  <%= render 'what_is' %>
  <h3>How do I start?</h3>
  <p>
    Just enter your email address over there to the right, and enter a description
    of your event.  You'll get two links: one for you, and one for your friends.
  </p>
<% end %>

<%= render 'form' %>

app/views/events/show.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag 'jquery.calendarSelect', 'showPage' %>
<% end %>

<% content_for :sidebar do %>
  <%= render 'what_is' %>
<% end %>

<% content_for :footer do %>
  <div id="preview">
    <hr />
    <div id="calendarSelect" class="static"></div>
  </div>
  <a href="#" id="showPreview">Show currently scheduled best times</a>
<% end %>

<div id="newTimeTable">
  <h3><%= @event.title %></h3>
  <h4>by <%= @event.email %></h4>
  <%= render 'time_tables/form' %>
  <%= hidden_field_tag :availability, @event.availability.to_json %>
  <%= hidden_field_tag :max_attendance, @event.max_attendance.to_json %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Schedule Butler</title>
  <script type="text/javascript" src="http://use.typekit.com/tcd3aid.js"></script>
  <%= javascript_include_tag 'loadTypekit' %>

  <%= stylesheet_link_tag 'tipTip.css', :media => 'screen, projection' %>
  <%= stylesheet_link_tag 'compiled/application.css', :media => 'screen, projection' %>
  <%= csrf_meta_tag %>
  <!--[if lt IE 8]>
    <%= stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection' %>
  <![endif]-->

</head>
<body>
  <div id="showgrid"></div>
  <div id="container">
    <div id="header">
      <h1><a href="/">Schedule Butler</a></h1>
      <h2>It's like having a butler to help you schedule</h2>
    </div>
    <div id="sidebar">
      <%= yield :sidebar %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
    <div id="footer">
      <%= yield :footer %>
    </div>
  </div>

  <%= javascript_include_tag 'jquery-1.4.2', 'jquery-ui-1.8.2.custom.min', 'rails', 'scheduleButler', 'jquery.tipTip.minified', 'jquery.contextmenu' %>
  <%= yield :javascripts %>
</body>
</html>

app/views/time_tables/_form.html.erb
<%= form_for([@event, @time_table]) do |f| %>
  <% if @event.errors.any? %>
  <div id="errorExplanation">
    <h3><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <div class="field">
    <%= f.label :email, "Please enter your email address" %>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit "Choose My Best Times" %>
  </div>
<% end %>

app/views/time_tables/_new_event_dialog.html.erb
<div id="newDialog" title="Welcome to Schedule Butler!">
  <div class="description">
    Congratulations, welcome to Schedule Butler!  You have just created a new event.
    To let your friends know about your event, all you have to do is send them an email
    with a link to the sign up page for your event.  This is provided for you below.
    If you want to come back to edit your own best times, just bookmark this page.
  </div>
  <div class="links">
    <p>Send your friends this url:</p>
    <div class="newEventUrl"><%= event_url(@event) %></div>
    <p>Bookmark this url for yourself:</p>
    <div class="newTimeTableUrl"><%= edit_event_time_table_url(@event, @time_table) %></div>
    <div class="buttons"><input type="button" id="newEventEmail" value="Send me an email with this info!" /></div>
  </div>
</div>

app/views/time_tables/_new_time_table_dialog.html.erb
<div id="newDialog" title="Welcome to Schedule Butler!">
  <div class="description">
    Congratulations, welcome to Schedule Butler!  You have just signed up for "<%= @event.title %>".
    The address of this page is your key to getting back here to update your times, so you should
    either write down the location of this page or bookmark it now.
  </div>
  <div class="links">
    <p>Bookmark this url in case your schedule changes:</p>
    <div class="newTimeTableUrl"><%= edit_event_time_table_url(@event, @time_table) %></div>      
    <div class="buttons"><input type="button" id="newTimeTableEmail" value="Send me an email with this info!" /></div>
  </div>
</div>

app/views/time_tables/_respondents.html.erb
<div id="respondentsDialog" title="People who have responded">
This is a list of all of the people who have responded to this event.
<ul>
  <% event.time_tables.map do |tt| %>
    <li><%= tt.email %></li>
  <% end %>
</ul>
</div>

app/views/time_tables/edit.html.erb
<% content_for(:javascripts) do %>  
  <%= javascript_include_tag('jquery.calendarSelect') %>
  <%= javascript_include_tag('editPage') %>
  <script type="text/javascript" src="http://www.google.com/jsapi?key=ABQIAAAATaAMXTegd0y6ylfgS2BWDxQ1PYv-JNNg2tVY2HS2bQLvfzrYORTt0jOgtwpSFSAcOIka_pKuXzDKzA"></script>
  <script type="text/javascript">google.load("gdata", "1");</script>
<% end %>

<% content_for(:sidebar) do %>
  <div id="eventTitle">
    <h3><%= @event.title %></h3>
    <h4>for <%= @time_table.email %></h4>
  </div>
<% end %>

<% content_for(:footer) do %>
  <div id="calendarSelect"></div>
  <%= hidden_field_tag :availability, @event.availability.to_json %>
  <%= hidden_field_tag :max_attendance, @event.max_attendance.to_json %>
  <%= form_for([@event, @time_table]) do |f| %>
    <%= f.hidden_field :times, :value => @times %>
    <div class="actions">
      <%= f.submit "Save My Changes" %>
    </div>
  <% end %>
  <img src="/images/pixel.gif" style="width: 1px; height: 1px;" />

  <%= render 'new_event_dialog' if flash[:new_event] %>
  <%= render 'new_time_table_dialog' if flash[:new_time_table] %>
  <%= render 'respondents', :event => @event %>
<% end %>

<input type="button" value="View people who have registered" id="showRespondentsDialog" />
<input type="button" value="Connect to Google Calendar" id="googleCalendarConnect" />
<input type="button" value="Disconnect from Google" id="googleCalendarDisconnect" />